# Beagleboard configuration

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_PROVIDES_INIT_RC := true
TARGET_NO_RADIOIMAGE := true
USE_CAMERA_STUB := true
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
BOARD_USES_VIRTUAL_TOUCHSCREEN := true
BOARD_USES_OMAP3_LIGHTS := true
BOARD_HAS_ARM_TLS_REG := true

# Setup some runtime system properties.
TARGET_BOARD_PLATFORM := omap3
TARGET_BOOTLOADER_BOARD_NAME := beagleboard
