# Beagleboard configuration

TARGET_NO_BOOTLOADER := true
TARGET_NO_KERNEL := true
TARGET_PROVIDES_INIT_RC := true
TARGET_NO_RADIOIMAGE := true
USE_CAMERA_STUB := true
BOARD_USES_ALSA_AUDIO := true
BUILD_WITH_ALSA_UTILS := true
BOARD_USES_VIRTUAL_TOUCHSCREEN := true
BOARD_USES_OMAP3_LIGHTS := true
USE_CUSTOM_RUNTIME_HEAP_MAX := "64M"
USE_CUSTOM_SURFACEFLINGER_HEAP_MAX := 16

# Setup some runtime system properties.
TARGET_BOARD_PLATFORM := omap3
TARGET_BOOTLOADER_BOARD_NAME := beagleboard
TARGET_CPU_ABI := armeabi

TARGET_ARCH_VARIANT := armv7-a
TARGET_HAVE_TSLIB := true

BOARD_WPA_SUPPLICANT_DRIVER := WEXT

WIFI_DRIVER_MODULE_PATH := /system/lib/modules/rt73usb.ko
WIFI_DRIVER_MODULE_USB_PATH := /system/lib/modules/rt2x00usb.ko
WIFI_DRIVER_MODULE_LIB_PATH := /system/lib/modules/rt2x00lib.ko
WIFI_DRIVER_MODULE_NAME := rt73usb
WIFI_DRIVER_MODULE_USB_NAME := rt2x00usb
WIFI_DRIVER_MODULE_LIB_NAME := rt2x00lib

QEMU_HARDWARE := true
